language: cpp
compiler: clang
sudo: false

# Install dependencies
addons:
  apt:
    packages:
      - libboost-test-dev -y
      - doxygen
      - graphviz

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen $TRAVIS_BUILD_DIR/Doxyfile

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T ip_print-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uevgenykol:$BINTRAY_API_KEY "https://api.bintray.com/content/evgenykol/otus_cpp_01/ip_print/$TRAVIS_BUILD_NUMBER/ip_print-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: html
    on:
      branch: master